ARCLeeds/arcleeds.github.io

- README.md
- _includes/_training-widget.html
- _sass/_09_elements.scss
- environment.yml
> Ngr testing

- _includes/_footer.html
- _includes/_navigation.html
resolves #22 and maximises accessibility
> fix #22 removes all target="_blank" in anchors

- _data/champs.yml
- pages/consultancy.md
> Nrfixchamps

- _includes/_footer.html
resolves strange footer column configuration for small viewports
> adjusted foundation specs for footer

- blog/_posts/2020-12-09-twelvedayshpc-Dec9.md
> day 7 blog post

- _data/widgets.yml
> Meaningful alt-text for images

- README.md
Added a few urls - Github pages and Jekyll
> Add some URLs

- _includes/_masthead.html
- _sass/_09_elements.scss
Adding temporary banner to arcleeds websites due to service outage
> added emergency banner to masthead

- blog/_posts/2021-12-02-twelvedayshpc2021-Dec02.md
opening PR for tomorrow for 12daysHPC
> adding blog post for day 2

- blog/_posts/2021-12-09-twelvedayshpc2021-Dec09.md
> 12dayshpc post 9

- blog/_posts/2021-12-10-twelvedayshpc2021-Dec10.md
> add post for day 10

- blog/_posts/2021-12-11-twelvedayshpc2021-Dec11.md
> adding post for day 11 12dayshpc

- blog/_posts/2021-12-12-twelvedayshpc2021-Dec12.md
> adding post for day 12 of 12dayshpc

- blog/_posts/2021-12-13-twelvedayshpc2021-Dec13.md
> 12days2021 day13

- blog/_posts/2021-12-14-twelvedayshpc2021-Dec14.md
> 12days2021 day14

- blog/_posts/2021-12-15-twelvedayshpc2021-Dec15.md
> 12days2021 day15

- blog/_posts/2021-12-16-twelvedayshpc2021-Dec16.md
> 12days2021 day16

- blog/_posts/2021-12-17-twelvedayshpc2021-Dec17.md
> 12days2021 day17

- blog/_posts/2021-12-18-twelvedayshpc2021-Dec18.md
> adding post for day 18

- blog/_posts/2020-12-01-twelvedayshpc-Dec1.md
- blog/_posts/2020-12-02-twelvedayshpc-Dec2.md
- blog/_posts/2020-12-03-twelvedayshpc-Dec3.md
- blog/_posts/2020-12-04-twelvedayshpc-Dec4.md
- blog/_posts/2020-12-07-twelvedayshpc-Dec7.md
- blog/_posts/2020-12-08-twelvedayshpc-Dec8.md
- blog/_posts/2020-12-09-twelvedayshpc-Dec9.md
- blog/_posts/2020-12-10-twelvedayshpc-Dec10.md
- blog/_posts/2020-12-11-twelvedayshpc-Dec11.md
- blog/_posts/2020-12-14-twelvedayshpc-Dec14.md
- blog/_posts/2020-12-15-twelvedayshpc-Dec15.md
- blog/_posts/2020-12-16-twelvedayshpc-Dec16.md
- blog/_posts/2020-12-17-twelvedayshpc-Dec17.md
- blog/_posts/2020-12-18-twelvedayshpc-Dec18-2.md
- blog/_posts/2020-12-18-twelvedayshpc-Dec18.md
- blog/_posts/2021-12-01-twelvedayshpc2021-Dec01.md
- blog/_posts/2021-12-02-twelvedayshpc2021-Dec02.md
- blog/_posts/2021-12-03-twelvedayshpc2021-Dec03.md
- blog/_posts/2021-12-04-twelvedayshpc2021-Dec04.md
- blog/_posts/2021-12-05-twelvedayshpc2021-Dec05.md
- blog/_posts/2021-12-06-twelvedayshpc2021-Dec06.md
- blog/_posts/2021-12-07-twelvedayshpc2021-Dec07.md
- blog/_posts/2021-12-08-twelvedayshpc2021-Dec08.md
- scripts/templates/12dayshpc-template.md.j2
I figure it should be High Performance Computing.
> Change capitalisation of High performance computing

- blog/_posts/2022-09-27-Winter2022TrainingCourses.md
Adds blog post with details of winter training sessions.
> add winter training blog post

- _data/rseday22.yml
Add my quote for the RSE day 2022
I tried to speak a little out of the box so it wouldn't get too repetitive.
Let me know if you think it's better if I talk more specifically about projects I've participated in.
> add Patricia's quote for rse day

- _data/rseday22.yml
> Rse day 2022 blog ngr

- _data/team.yml
- pages/about/team.md
Updated team page to reflect changes to the team and that DAT are a separate but related team.
> reformatted team page

- blog/_posts/2022-12-03-twelvedayshpc2022-Dec03.md
> add post for day 3

- blog/_posts/2023-04-19-conda-r-geospatial.md
This PR adds a blog post all about using conda on ARC4 to manage R dependencies for geospatial packages.
@jhodrien wonder what this would be like with spack?
> Add blog post about using conda on ARC4 to build R geospatial libraries

- blog/_posts/2023-04-25-nutrientprofiler-r-pkg.md
This PR adds a blog post that talks generally about the experience of building an R package as well as talking a little bit about the `nutrientprofiler` package created for an RSE project with the CDRC.
> Blog post about building R packages and `nutrientprofiler`

- _data/team.yml
This PR updates team section to reflect me leaving the team. Scheduling for the day after my last day.
/schedule 2023-05-06
> Update team section to reflect changes

- blog/_posts/2023-06-01-Summer2023TrainingCourses.md
It is a copy from previous blogs.
So, the most important is to double checking the dates & times.
Thanks
> Add blog post with course dates - summer 2023

- _config.yml
- _data/socialmedia.yml
I have not tested the build of the Website, but I think there should be no problem with these changes.
> Update/edit Twitter account details

- _data/training_courses.yml
- pages/training/training_courses/hpc0.md
> 189 update hpc0

- _data/team.yml
- _includes/_about-widget.html
- pages/about/team.md
I managed to figure out the automatic sorting - at the moment all it does is swap Ollie and Mark, so I also created a Management section at the top as the current order seems sensible, though isn't alphabetical.
> 113 sorting team data by surname alphabetically

- blog/_posts/2023-09-22-Autumn2023TrainingCourses.md
- pages/training/training_courses/swd1b.md
This PR creates a blog with all dates and info related with our Autumn Courses.
It also includes a variable fix in the SWD1b page. In the moment is not loading any inoformation from the `_data/training_courses.yml` file.
> 2023 autumn training

- blog/_posts/2023-09-22-Autumn2023TrainingCourses.md
- pages/training/training_courses/swd1b.md
Add @jhodrien Fixes.
This is necessary because I merged the PR before see his review. Sorry 😭
> add John's fixes for PR #217

- _data/bitesize-videos.yml
- pages/help/help_videos.md
Removes videos that expose login information.
Also removed missing video.
> Remove videos with login details

- pages/research_platforms.md
This PR add to the Research Platforms page:
- Roadmap
- A more detailed list of resources
All the content was drafted in a meeting with @jhodrien;
It is the first draft of the content, as more and more details can be added, but I don't want to spend days going in one direction if it is not the right one.
The tables are in `html` because I want to include bullet points in the cells; the wordpress is in html as well, so I didn't bother to find a different solution.
> Platform update
